#!/usr/bin/env node
'use strict';

/*
 * Case study generator for luch.dev.
 *
 * Reads content/portfolio/*.md (frontmatter + a constrained markdown
 * dialect), renders each `status: ready` case through the block library the
 * template page (template.html) specifies, and writes:
 *
 *   portfolio/<slug>/index.html      the page (JSON-LD embedded)
 *   portfolio/<slug>/index.html.md   the markdown twin for LLMs
 *   sitemap.xml                      home + every published case
 *   llms.txt                         case lines between the cases markers
 *
 * Generated files carry a header comment and are committed — the deploy
 * workflow just copies files, and pages stay openable straight from disk
 * (all paths relative).
 *
 * Markdown dialect → blocks (see .claude/skills/case-study/SKILL.md):
 *   ## Heading                        starts a section
 *
 * Two summary fields, deliberately: `summary` is the ≤160-char one-liner the
 * meta description, og:description, home card and llms.txt all quote, so it
 * cannot grow; `tldr` is the longer paragraph the page's own TL;DR block
 * shows, and falls back to `summary` when a case doesn't set it.
 *   paragraph                         Text
 *   bullet list                       List
 *   ![brief](placeholder:id "W:H")   grey placeholder figure
 *   ![alt](file.webp "W:H")          real figure from assets/projects/<slug>/
 *   > quote ... — **Name**, Role [source](url)   Quote (clickable if url)
 *   ```lang fenced code               Code
 *   GFM table                         Table
 *   raw HTML                          passed through (escape hatch)
 *
 * Anything before the first ## renders into the hero section under the H1.
 */

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const { marked } = require('marked');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://luch.dev';

// ------------------------------------------------------------------ cli --

const args = process.argv.slice(2);
function argValue(name, fallback) {
  const i = args.indexOf(name);
  return i !== -1 && args[i + 1] ? args[i + 1] : fallback;
}
const CONTENT_DIR = path.resolve(ROOT, argValue('--content', 'content/portfolio'));
const OUT_ROOT = path.resolve(ROOT, argValue('--out', '.'));

// ---------------------------------------------------------------- helpers --

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

const inline = (md) => marked.parseInline(String(md ?? ''));

// "598 / 395" from a "W:H" or "W/H" ratio hint; default 3:2
function arFromHint(hint) {
  const m = /^\s*([\d.]+)\s*[:/]\s*([\d.]+)\s*$/.exec(hint || '');
  return m ? `${m[1]} / ${m[2]}` : '3 / 2';
}

const GENERATED_NOTE = (src) =>
  `<!-- Generated by tools/build.js from ${src} — edit the source, not this file. -->`;

// ------------------------------------------------------------ validation --

function validate(fm, file) {
  const errors = [];
  const warn = [];
  for (const k of ['title', 'slug', 'summary', 'status']) {
    if (!fm[k]) errors.push(`missing required field: ${k}`);
  }
  if (fm.summary && fm.summary.length > 160) {
    errors.push(`summary is ${fm.summary.length} chars (max 160)`);
  }
  /* The aside is a narrow column — past roughly this length the TL;DR stops
     being a summary and becomes the case study told twice. */
  if (fm.tldr && fm.tldr.length > 500) {
    warn.push(`tldr is ${fm.tldr.length} chars — long for the aside (aim under 500)`);
  }
  if (fm.slug && !/^[a-z0-9-]+$/.test(fm.slug)) {
    errors.push(`slug must be kebab-case: "${fm.slug}"`);
  }
  for (const l of fm.links || []) {
    if (!l.label || !l.url) warn.push(`link with empty label or url`);
  }
  for (const m of fm.metrics || []) {
    if (!m.label) warn.push(`metric with empty label`);
  }
  if (!fm.headline) warn.push('no headline — falling back to title');
  return { errors, warn };
}

// ------------------------------------------------------ markdown → blocks --

// Split the body into sections on H2; each section is rendered from block
// primitives. Returns { heroTokens, sections: [{title, tokens}] }.
function sectionise(tokens) {
  const hero = [];
  const sections = [];
  let current = null;
  for (const t of tokens) {
    if (t.type === 'heading' && t.depth === 2) {
      current = { title: t.text, tokens: [] };
      sections.push(current);
    } else if (current) {
      current.tokens.push(t);
    } else {
      hero.push(t);
    }
  }
  return { hero, sections };
}

// A paragraph that is exactly one image is a figure, not a Text block.
function soleImage(token) {
  if (token.type !== 'paragraph' || !token.tokens) return null;
  const meaningful = token.tokens.filter((t) => !(t.type === 'text' && !t.text.trim()));
  return meaningful.length === 1 && meaningful[0].type === 'image' ? meaningful[0] : null;
}

function renderFigure(img, slug) {
  const ar = arFromHint(img.title);
  if (img.href.startsWith('placeholder:')) {
    const id = img.href.slice('placeholder:'.length);
    return `<figure class="figure" style="--ar: ${ar}">
          <div class="figure__media">
            <p class="figure__brief">${esc(img.text)}</p>
            <span class="figure__id">placeholder:${esc(id)}</span>
          </div>
        </figure>`;
  }
  const src = /^(https?:)?\//.test(img.href) || img.href.startsWith('../')
    ? img.href
    : `../../assets/projects/${slug}/${img.href}`;
  return `<figure class="figure">
          <div class="figure__media" style="--ar: ${ar}">
            <img src="${esc(src)}" alt="${esc(img.text)}" loading="lazy" decoding="async" />
          </div>
        </figure>`;
}

// Quote: last blockquote paragraph starting with an em dash is attribution;
// its first link is the source the whole card links out to.
function renderQuote(token) {
  const paras = token.tokens.filter((t) => t.type === 'paragraph');
  let attribution = null;
  let quoteParas = paras;
  const last = paras[paras.length - 1];
  if (last && /^\s*[—-]\s*/.test(last.text)) {
    attribution = last;
    quoteParas = paras.slice(0, -1);
  }
  const quoteHtml = quoteParas.map((p) => `<p>${inline(p.text)}</p>`).join('\n            ');

  let url = null;
  let attribText = '';
  if (attribution) {
    const linkTok = (attribution.tokens || []).find((t) => t.type === 'link');
    if (linkTok) url = linkTok.href;
    attribText = attribution.text
      .replace(/^\s*[—-]\s*/, '')
      .replace(/\s*\[([^\]]*)\]\([^)]*\)\s*$/, '') // drop the trailing [source](url)
      .trim();
  }

  const footer = attribution
    ? `\n            <footer>
              <cite>${inline(attribText)}</cite>${url ? `
              <svg class="icon quote__link-icon" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                <path d="M21 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6" />
                <path d="m21 3-9 9" />
                <path d="M15 3h6v6" />
              </svg>` : ''}
            </footer>`
    : '';

  const inner = `<blockquote>
            ${quoteHtml}${footer}
          </blockquote>`;

  return url
    ? `<a class="quote" href="${esc(url)}" target="_blank" rel="noopener noreferrer">
          ${inner}
        </a>`
    : `<div class="quote">
          ${inner}
        </div>`;
}

function renderCode(token) {
  return `<figure class="code-figure">
          <pre class="code-block"><code>${esc(token.text)}</code></pre>
        </figure>`;
}

function renderTable(token) {
  const head = token.header
    .map((c) => `<th scope="col">${inline(c.text)}</th>`)
    .join('');
  const body = token.rows
    .map((row) => `<tr>${row.map((c) => `<td>${inline(c.text)}</td>`).join('')}</tr>`)
    .join('\n              ');
  return `<div class="table-scroll">
          <table class="case-table">
            <thead><tr>${head}</tr></thead>
            <tbody>
              ${body}
            </tbody>
          </table>
        </div>`;
}

function renderList(token) {
  const items = token.items
    .map((it) => `<li>${inline(it.text)}</li>`)
    .join('\n          ');
  return `<ul>
          ${items}
        </ul>`;
}

function renderTokens(tokens, slug) {
  const out = [];
  for (const t of tokens) {
    const img = soleImage(t);
    if (img) out.push(renderFigure(img, slug));
    else if (t.type === 'paragraph') out.push(`<p>${inline(t.text)}</p>`);
    else if (t.type === 'list') out.push(renderList(t));
    else if (t.type === 'blockquote') out.push(renderQuote(t));
    else if (t.type === 'code') out.push(renderCode(t));
    else if (t.type === 'table') out.push(renderTable(t));
    else if (t.type === 'html') out.push(t.text.trim());
    else if (t.type === 'space') continue;
    else if (t.type === 'heading') out.push(`<h${t.depth}>${inline(t.text)}</h${t.depth}>`);
    else console.warn(`  ! unhandled markdown token: ${t.type}`);
  }
  return out.join('\n\n        ');
}

// ----------------------------------------------------------------- icons --

const ICONS = {
  arrowLeft: `<svg class="icon" viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path d="m12 19-7-7 7-7" />
        <path d="M19 12H5" />
      </svg>`,
  calendar: `<svg class="icon" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path d="M8 2v3" />
              <path d="M16 2v3" />
              <rect x="3" y="3" width="18" height="18" rx="2" />
              <path d="M3 9h18" />
            </svg>`,
  building: `<svg class="icon" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path d="M10 12h4" />
              <path d="M10 8h4" />
              <path d="M14 21v-3a2 2 0 0 0-4 0v3" />
              <path d="M6 10H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-2" />
              <path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16" />
            </svg>`,
  smile: `<svg class="icon" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <path d="M15 10V9" />
              <path d="M16.472 15a6 6 0 0 1-8.943 0" />
              <path d="M9 10V9" />
              <circle cx="12" cy="12" r="10" />
            </svg>`,
  network: `<svg class="icon" viewBox="0 0 24 24" fill="none" aria-hidden="true">
              <rect x="16" y="16" width="6" height="6" rx="1" />
              <rect x="2" y="16" width="6" height="6" rx="1" />
              <rect x="9" y="2" width="6" height="6" rx="1" />
              <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
              <path d="M12 12V8" />
            </svg>`,
};

// --------------------------------------------------------------- json-ld --

function jsonLd(fm) {
  const url = `${SITE}/portfolio/${fm.slug}/`;
  const app = {
    '@type': 'MobileApplication',
    name: fm.title,
    applicationCategory: fm.category || undefined,
    operatingSystem: (fm.platform || []).join(', ') || undefined,
    author: { '@type': 'Person', name: 'Ulad Luch', url: `${SITE}/` },
  };
  const rating = (fm.metrics || []).find((m) => m.kind === 'rating' && m.value);
  if (rating) {
    app.aggregateRating = {
      '@type': 'AggregateRating',
      ratingValue: rating.value,
      bestRating: 5,
    };
  }
  const store = (fm.links || []).find((l) => /app store|google play/i.test(l.label || ''));
  if (store) app.installUrl = store.url;

  const graph = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'CreativeWork',
        name: fm.headline || fm.title,
        description: fm.summary,
        url,
        author: { '@type': 'Person', name: 'Ulad Luch', url: `${SITE}/` },
        about: app,
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Portfolio', item: `${SITE}/` },
          { '@type': 'ListItem', position: 2, name: fm.title, item: url },
        ],
      },
    ],
  };
  return JSON.stringify(graph, null, 2);
}

// ------------------------------------------------------------- page shell --

function renderPage(fm, body, srcRel) {
  const passportRows = [];
  if (fm.company) {
    const name = fm.companyUrl
      ? `<a href="${esc(fm.companyUrl)}" target="_blank" rel="noopener noreferrer">${esc(fm.company)}</a>`
      : esc(fm.company);
    passportRows.push(`<li>
            ${ICONS.building}
            Company: ${name}
          </li>`);
  }
  if (fm.period) passportRows.push(`<li>
            ${ICONS.calendar}
            Timeline: ${esc(fm.period)}
          </li>`);
  if (fm.role) passportRows.push(`<li>
            ${ICONS.smile}
            Role: ${esc(fm.role)}
          </li>`);

  const linkItems = (fm.links || [])
    .filter((l) => l.label && l.url)
    .map((l) => `<li><a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">${esc(l.label)}</a></li>`)
    .join('\n          ');

  const heroHtml = body.heroHtml ? `\n        ${body.heroHtml}` : '';
  const sectionsHtml = body.sections
    .map((s) => `<section class="case-section">
        <h2>${inline(s.title)}</h2>

        ${s.html}
      </section>`)
    .join('\n\n\n      ');

  return `<!DOCTYPE html>
${GENERATED_NOTE(srcRel)}
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${esc(fm.title)} — Ulad Luch</title>
  <meta name="description" content="${esc(fm.summary)}" />
  <meta name="author" content="Ulad Luch" />
  <meta name="robots" content="index,follow" />
  <meta name="theme-color" content="#f9fafb" />
  <link rel="canonical" href="${SITE}/portfolio/${fm.slug}/" />
  <link rel="alternate" type="text/markdown" href="index.html.md" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="${esc(fm.title)} — Ulad Luch" />
  <meta property="og:description" content="${esc(fm.summary)}" />
  <meta property="og:url" content="${SITE}/portfolio/${fm.slug}/" />
  <link rel="icon" href="../../assets/favicon.png" type="image/png" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="../../main.css" />
  <script type="application/ld+json">
${jsonLd(fm)}
  </script>
</head>
<body>

  <header class="topbar">
    <div class="topbar__inner">
    <a class="icon-button" href="../../index.html" aria-label="Back to home">
      ${ICONS.arrowLeft}
    </a>

    <a class="mark" href="../../index.html" aria-label="Ulad Luch home">
      <img src="../../assets/logo.svg" width="32" height="32" alt="" />
    </a>

    <a class="icon-button" href="mailto:hello@luch.dev" aria-label="Get in touch">
      ${ICONS.calendar}
    </a>
    </div>
  </header>

  <main class="case-layout">

    <aside class="case-aside">
      <section class="case-block">
        <h3 class="case-block__title">Project Details</h3>
        <ul class="detail-list">
          ${passportRows.join('\n          ')}
        </ul>
      </section>

      <hr class="rule" />

      <section class="case-block">
        <h3 class="case-block__title">TL;DR</h3>
        <p>${inline(fm.tldr || fm.summary)}</p>
      </section>

      <hr class="rule" />

      <section class="case-block">
        <h3 class="case-block__title">Links</h3>
        <ul class="link-list">
          ${linkItems}
        </ul>
      </section>

      <hr class="rule" />
    </aside>

    <article class="case-article">

      <section class="case-section">
        <h1>${inline(fm.headline || fm.title)}</h1>${heroHtml}
      </section>


      ${sectionsHtml}

    </article>

  </main>

  <script src="../../main.js"></script>
</body>
</html>
`;
}

// ------------------------------------------------------------------ twin --

function renderTwin(fm, rawBody, srcRel) {
  // Placeholders carry no image yet; the twin says so in words.
  const body = rawBody
    .replace(/!\[([^\]]*)\]\(placeholder:[^)]*\)/g, '*[Planned figure: $1]*')
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim();

  const passport = [
    fm.company ? `- Company: ${fm.company}${fm.companyUrl ? ` (${fm.companyUrl})` : ''}` : null,
    fm.period ? `- Timeline: ${fm.period}` : null,
    fm.role ? `- Role: ${fm.role}` : null,
    (fm.metrics || []).length
      ? `- Impact: ${(fm.metrics || []).map((m) => m.label).filter(Boolean).join(' • ')}`
      : null,
  ].filter(Boolean).join('\n');

  const links = (fm.links || [])
    .filter((l) => l.label && l.url)
    .map((l) => `- [${l.label}](${l.url})`)
    .join('\n');

  return `${GENERATED_NOTE(srcRel)}

# ${fm.headline || fm.title}

> ${fm.summary}

${passport}

${body}

## Links

${links}
`;
}

// --------------------------------------------------------- sitemap / llms --

function writeSitemap(cases) {
  const today = new Date().toISOString().slice(0, 10);
  const urls = [
    `${SITE}/`,
    ...cases.map((c) => `${SITE}/portfolio/${c.slug}/`),
  ];
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/build.js — edit content/, not this file. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url>
    <loc>${u}</loc>
    <lastmod>${today}</lastmod>
  </url>`).join('\n')}
</urlset>
`;
  fs.writeFileSync(path.join(OUT_ROOT, 'sitemap.xml'), xml);
}

const CASES_START = '<!-- cases:start — generated by tools/build.js -->';
const CASES_END = '<!-- cases:end -->';

function updateLlms(cases) {
  const llmsPath = path.join(OUT_ROOT, 'llms.txt');
  const lines = cases
    .map((c) => `- [${c.title}](${SITE}/portfolio/${c.slug}/index.html.md): ${c.summary}`)
    .join('\n');
  const block = `${CASES_START}\n${lines}\n${CASES_END}`;

  let text = fs.existsSync(llmsPath) ? fs.readFileSync(llmsPath, 'utf8') : '';
  if (text.includes(CASES_START)) {
    text = text.replace(
      new RegExp(`${CASES_START}[\\s\\S]*?${CASES_END}`),
      block
    );
  } else if (text) {
    text = text.trimEnd() + `\n\n## Case studies\n\n${block}\n`;
  } else {
    text = `## Case studies\n\n${block}\n`;
  }
  fs.writeFileSync(llmsPath, text);
}

// ------------------------------------------------------------------ main --

function main() {
  const files = fs.readdirSync(CONTENT_DIR)
    .filter((f) => f.endsWith('.md') && !f.startsWith('_'));

  const published = [];
  let failed = false;

  for (const file of files) {
    const srcAbs = path.join(CONTENT_DIR, file);
    const srcRel = path.relative(ROOT, srcAbs);
    const raw = fs.readFileSync(srcAbs, 'utf8');

    const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(raw);
    if (!m) { console.error(`✗ ${file}: no frontmatter`); failed = true; continue; }

    let fm;
    try { fm = yaml.load(m[1]); }
    catch (e) { console.error(`✗ ${file}: bad YAML — ${e.message}`); failed = true; continue; }

    const { errors, warn } = validate(fm, file);
    for (const w of warn) console.warn(`  ~ ${file}: ${w}`);
    if (errors.length) {
      for (const e of errors) console.error(`✗ ${file}: ${e}`);
      failed = true;
      continue;
    }

    if (fm.status !== 'ready') {
      console.log(`- ${file}: status "${fm.status}" — skipped`);
      continue;
    }

    const tokens = marked.lexer(m[2]);
    const { hero, sections } = sectionise(tokens);

    const heroImg = hero.map(soleImage).find(Boolean);
    const heroHtml = heroImg ? renderFigure(heroImg, fm.slug) : '';
    const heroRest = hero.filter((t) => !soleImage(t));
    const heroExtra = heroRest.length ? renderTokens(heroRest, fm.slug) : '';

    const body = {
      heroHtml: [heroHtml, heroExtra].filter(Boolean).join('\n\n        '),
      sections: sections.map((s) => ({
        title: s.title,
        html: renderTokens(s.tokens, fm.slug),
      })),
    };

    const dir = path.join(OUT_ROOT, 'portfolio', fm.slug);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'index.html'), renderPage(fm, body, srcRel));
    fs.writeFileSync(path.join(dir, 'index.html.md'), renderTwin(fm, m[2], srcRel));
    console.log(`✓ ${file} → portfolio/${fm.slug}/`);
    published.push(fm);
  }

  if (published.length) {
    writeSitemap(published);
    updateLlms(published);
    console.log(`✓ sitemap.xml + llms.txt updated (${published.length} case${published.length > 1 ? 's' : ''})`);
  } else {
    console.log('- no ready cases; sitemap/llms untouched');
  }

  if (failed) process.exit(1);
}

main();
